### ISSUE TITLE
Disallow `?` in setting name

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/habitat#35]
`setting something_happened? : Bool` should raise at compile time and say that the method will automatically have a `?` if the type is a Bool

**Comment by jwoertink** [comment]
It looks like the predicate methods exist on all types for being possibly nilable. https://github.com/luckyframework/habitat/blob/master/src/habitat.cr#L205-L207

What we could do here is change that method to only exist on bool methods, and then the method above it can set to have a type of `Whatever` if it's not nilable and `Whatever?` if it is
