### ISSUE TITLE
Examples don't work when used with a class

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/habitat#37]
```
Unhandled exception: The 'logger' setting for Lucky was nil, but the setting is required.

Try this...

  Lucky.configure do |settings|
    settings.logger = Nil # Uh-oh
  end
```

**Comment by jwoertink** [comment]
I'm not sure what the original code looked like for this, but I do know you can use constants as values for settings. The other thing though is, if `logger` is nilable, then you shouldn't need to set a value, but if it's not nilable, then setting it to the `Nil` constant doesn't really make sense 🤔 

I opened up #62 for testing this. So I think it's ok to close this, but if you happen to remember the real test case for this, or maybe I'm missing something, let me know.

**Comment by jwoertink** [comment]
reopening because I have a new way to cause this
